# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4fdd\u5b58\u65e5\u671f')),
            ],
        ),
    ]
